shorten_quintet_cols <- function(x) {
    x <- tolower(x)
    x <- gsub("\\s+", "_", x)
    x <- gsub("[()]+", "", x)
    x <- gsub("__+", "_", x)

    # Prefix shortening
    x <- sub("^common_", "cm_", x)
    x <- sub("^securities_trade_instrument_", "sti_", x)
    x <- sub("^securities_trade_account_", "sta_", x)
    x <- sub("^securities_trade_", "st_", x)
    x <- sub("^cash_order_", "co_", x)
    x <- sub("^securities_delivery_instrument_", "sdi_", x)
    x <- sub("^securities_delivery_cash__account_", "sdc_", x)
    x <- sub("^securities_delivery_investment__account_", "sdiacc_", x)
    x <- sub("^securities_delivery_", "sd_", x)
    x <- sub("^foreign_exchange_trade_", "fxt_", x)
    x <- sub("^foreign_exchange_account_", "fxa_", x)
    x <- sub("^foreign_exchange_", "fx_", x)
    x <- sub("^customer_deposit_exchange_", "cdx_", x)
    x <- sub("^customer_foreign_exchange_", "cfx_", x)
    x <- sub("^customer_deposit_", "cd_", x)
    x <- sub("^account_", "acct_", x)
    x <- sub("^ca_instrument_", "cai_", x)
    x <- sub("^ca_trade_", "cat_", x)
    x <- sub("^custody_trade_", "ct_", x)

    # Tidy extra underscores
    x <- gsub("__+", "_", x)
    x <- gsub("_+$", "", x)

    make.unique(x)
}

cfg <- list(
    cshnxc = list(
        file = list(
            pattern = "^G000359_.*_Global_CshNxc_JRN_[0-9]{4}-[0-9]{2}-[0-9]{2}_.*_CSV\\.csv$",
            cols_raw = c(
                "client_id",
                "transaction_reference",
                "operation_direction",
                "value_date",
                "operation_date",
                "quantity",
                "operation_currency",
                "operation_type_code",
                "transaction_description",
                "client_reference",
                "exchange_value_(eur)",
                "exchange_value_rate",
                "iban",
                "kbl_cash_account_number",
                "client_name",
                "account_title",
                "account_type",
                "account_currency"
            ),
            date_cols = c("value_date", "operation_date"),
            date_formats = c("%d.%m.%Y"),
            add_filename_date = TRUE,
            filename_date_col = "as_of_date",
            filename_date_fmt = "%Y-%m-%d",
            filename_date_regex = "JRN_([0-9]{4}-[0-9]{2}-[0-9]{2})_",
            sep = ";"
        ),
        db = list(
            table = "cashtransactions",
            keys = c("client_id", "transaction_reference", "operation_date", "operation_currency", "iban", "quantity")
        )
    ),

    titnxc = list(
        file = list(
            pattern = "^G000359_.*_Global_TitNxc_JRN_[0-9]{4}-[0-9]{2}-[0-9]{2}_.*_CSV\\.csv$",
            cols_raw = c(
                "client_id",
                "transaction_reference",
                "type",
                "quantity",
                "creation_date",
                "value_date",
                "market_price",
                "price_currency",
                "rate_type",
                "operation_type_code",
                "weighted_average_cost",
                "internal_reference",
                "kbl_code_identifying_security_used",
                "isin_code",
                "telekurs_code",
                "sedol_code",
                "description_of_security",
                "type_of_financial_instrument",
                "complementary_type",
                "expression_type",
                "currency_code",
                "vni_frequency",
                "place_of_listing",
                "calculation_basis",
                "contract_size",
                "strike_price",
                "currency_strike_price",
                "maturity_date",
                "interest_type",
                "interest_rate_in_percentage",
                "coupon_periodicity",
                "coupon_maturity",
                "issue_date",
                "issue_nominal_amount",
                "issue_nominal_amount_currency",
                "indicator_issue_emission",
                "indicateur_equalization_factor",
                "rating_s&p",
                "economic_sector",
                "kbl_account_number",
                "account_name",
                "client_name"
            ),
            date_cols = c("creation_date", "value_date", "maturity_date", "issue_date"),
            date_formats = c("%d.%m.%Y"),
            add_filename_date = TRUE,
            filename_date_col = "as_of_date",
            filename_date_fmt = "%Y-%m-%d",
            filename_date_regex = "JRN_([0-9]{4}-[0-9]{2}-[0-9]{2})_",
            sep = ";"
        ),
        db = list(
            table = "securitytransactions",
            keys = c("client_id", "transaction_reference", "operation_type_code", "isin_code")
        )
    ),

    cshstmt = list(
        file = list(
            pattern = "^G000359_.*_Global_CshStmt_JRN_[0-9]{4}-[0-9]{2}-[0-9]{2}_.*_CSV\\.csv$",
            cols_raw_src = c(
                "common_client_id",
                "common_client_name",
                "common_account_title",
                "common_iban",
                "common_kbl_cash_account_number",
                "common_transaction_currency",
                "common_transaction_type",
                "common_transaction_reference",
                "common_transaction_name",
                "common_value_date",
                "common_accounting_date",
                "common_account_type",
                "common_movement_amount",
                "common_accounting_balance",
                "common_previous_balance",
                "common_statement_number",
                "securities_trade_instrument_kbl_code_identifying_security_used",
                "securities_trade_instrument_isin_code",
                "securities_trade_instrument_telekurs_code",
                "securities_trade_instrument_sedol_code",
                "securities_trade_instrument_description_of_security",
                "securities_trade_instrument_type_of_financial_instrument",
                "securities_trade_instrument_complementary_type",
                "securities_trade_instrument_expression_type",
                "securities_trade_instrument_currency_code",
                "securities_trade_instrument_vni_frequency",
                "securities_trade_instrument_place_of_listing",
                "securities_trade_instrument_calculation_basis",
                "securities_trade_instrument_contract_size",
                "securities_trade_instrument_strike_price",
                "securities_trade_instrument_currency_strike_price",
                "securities_trade_instrument_maturity_date",
                "securities_trade_instrument_interest_type",
                "securities_trade_instrument_interest_rate_in_percentage",
                "securities_trade_instrument_coupon_periodicity_(dd/mm)",
                "securities_trade_instrument_coupon_maturity",
                "securities_trade_instrument_issue_date",
                "securities_trade_instrument_issue_nominal_amount",
                "securities_trade_instrument_issue_nominal_amount_currency",
                "securities_trade_instrument_indicator_issue_emission",
                "securities_trade_instrument_indicateur_equalization_factor",
                "securities_trade_instrument_rating_s&p",
                "securities_trade_instrument_economic_sector",
                "securities_trade_account_kbl_account_number",
                "securities_trade_account_account_name",
                "securities_trade_account_client_name",
                "securities_trade_order_type",
                "securities_trade_market_type",
                "securities_trade_ordered_quantity",
                "securities_trade_ordered_nominal_amount",
                "securities_trade_ordered_nominal_amount_currency",
                "securities_trade_ordered_amount",
                "securities_trade_ordered_amount_currency",
                "securities_trade_place_of_trade_(mic_code)",
                "securities_trade_best_execution_indicator",
                "securities_trade_client_reference",
                "securities_trade_order_reference",
                "securities_trade_deal_reference",
                "securities_trade_order_date_time",
                "securities_trade_prepye_indicator",
                "securities_trade_prepye_amount",
                "securities_trade_prepye_amount_currency",
                "securities_trade_pool_factor",
                "securities_trade_dirty_price_indicator",
                "securities_trade_interest_accrued_days_number",
                "securities_trade_tax_income_per_share",
                "securities_trade_tax_income_per_share_currency",
                "securities_trade_partially_execution_indicator",
                "securities_trade_cancellation_indicator",
                "securities_trade_quantity_settled",
                "securities_trade_nominal_amount_settled",
                "securities_trade_nominal_amount_settled_currency",
                "securities_trade_averaged_gross_price",
                "securities_trade_dealing_price_currency",
                "securities_trade_trade_date_time",
                "securities_trade_cash_settlement_date",
                "securities_trade_gross_amount",
                "securities_trade_gross_amount_currency",
                "securities_trade_net_amount",
                "securities_trade_net_amount_currency",
                "securities_trade_securities_trade_list_costs_details",
                "cash_order_cash_order_number",
                "cash_order_cash_order_client_number",
                "cash_order_client_reference",
                "cash_order_cash_order_date_time",
                "cash_order_remitter_account_number",
                "cash_order_remitter_bank_bic_code",
                "cash_order_remitter_bank_name",
                "cash_order_remitter_address_1",
                "cash_order_remitter_address_2",
                "cash_order_remitter_address_3",
                "cash_order_remitter_address_4",
                "cash_order_debitor_account_holder",
                "cash_order_debitor_account_number",
                "cash_order_debitor_cash_amount",
                "cash_order_debitor_cash_amount_currency",
                "cash_order_debitor_value_date",
                "cash_order_debitor_iblc_category",
                "cash_order_debitor_iblc_category_code",
                "cash_order_debitor_iblc_country_code",
                "cash_order_debitor_iblc_reason_code",
                "cash_order_debitor_advice_number",
                "cash_order_creditor_account_holder",
                "cash_order_creditor_account_number",
                "cash_order_creditor_iblc_category",
                "cash_order_creditor_iblc_category_code",
                "cash_order_creditor_iblc_country_code",
                "cash_order_creditor_iblc_reason_code",
                "cash_order_creditor_advice_number",
                "cash_order_beneficiary_name",
                "cash_order_beneficiary_account_number",
                "cash_order_beneficiary_bank_bic_code",
                "cash_order_beneficiary_bank_name",
                "cash_order_correspondent_bank_bic_code",
                "cash_order_correspondent_bank_name",
                "cash_order_communication_1",
                "cash_order_communication_2",
                "cash_order_communication_3",
                "cash_order_communication_4",
                "cash_order_charge_type",
                "cash_order_cash_order_list_costs_details",
                "securities_delivery_instrument_kbl_code_identifying_security_used",
                "securities_delivery_instrument_isin_code",
                "securities_delivery_instrument_telekurs_code",
                "securities_delivery_instrument_sedol_code",
                "securities_delivery_instrument_description_of_security",
                "securities_delivery_instrument_type_of_financial_instrument",
                "securities_delivery_instrument_complementary_type",
                "securities_delivery_instrument_expression_type",
                "securities_delivery_instrument_currency_code",
                "securities_delivery_instrument_vni_frequency",
                "securities_delivery_instrument_place_of_listing",
                "securities_delivery_instrument_calculation_basis",
                "securities_delivery_instrument_contract_size",
                "securities_delivery_instrument_strike_price",
                "securities_delivery_instrument_currency_strike_price",
                "securities_delivery_instrument_maturity_date",
                "securities_delivery_instrument_interest_type",
                "securities_delivery_instrument_interest_rate_in_percentage",
                "securities_delivery_instrument_coupon_periodicity_(dd/mm)",
                "securities_delivery_instrument_coupon_maturity",
                "securities_delivery_instrument_issue_date",
                "securities_delivery_instrument_issue_nominal_amount",
                "securities_delivery_instrument_issue_nominal_amount_currency",
                "securities_delivery_instrument_indicator_issue_emission",
                "securities_delivery_instrument_indicateur_equalization_factor",
                "securities_delivery_instrument_rating_s&p",
                "securities_delivery_instrument_economic_sector",
                "securities_delivery_cash__account_iban",
                "securities_delivery_cash__account_kbl_account_number",
                "securities_delivery_cash__account_client_name",
                "securities_delivery_cash__account_account_title",
                "securities_delivery_cash__account_account_type",
                "securities_delivery_cash__account_account_currency",
                "securities_delivery_investment__account_kbl_account_number",
                "securities_delivery_investment__account_account_name",
                "securities_delivery_investment__account_client_name",
                "securities_delivery_settlement_operation_status",
                "securities_delivery_counterparty_type",
                "securities_delivery_counterparty",
                "securities_delivery_securities_account_identifier",
                "securities_delivery_safekeeping_account_identifier",
                "securities_delivery_processing_reference",
                "securities_delivery_trade_kb_operation_id",
                "securities_delivery_trade_client_operation_reference",
                "securities_delivery_trade_trade_status",
                "securities_delivery_trade_trade_date",
                "securities_delivery_trade_swift_notification_date",
                "securities_delivery_trade_place_of_trade",
                "securities_delivery_trade_settlement_date",
                "securities_delivery_trade_effective_settlement_date",
                "securities_delivery_trade_operation_direction",
                "securities_delivery_trade_quantity",
                "securities_delivery_trade_amount",
                "securities_delivery_trade_amount_currency",
                "foreign_exchange_trade_deal_number",
                "foreign_exchange_trade_operation_type",
                "foreign_exchange_trade_deal_date",
                "foreign_exchange_trade_value_date",
                "foreign_exchange_trade_maturity_date_(swaps_only)",
                "foreign_exchange_trade_operation_direction",
                "foreign_exchange_trade_currency_1",
                "foreign_exchange_trade_currency_1_amount",
                "foreign_exchange_trade_counter_currency",
                "foreign_exchange_trade_counter_currency_amount",
                "foreign_exchange_trade_exchange_rate",
                "foreign_exchange_trade_forward_currency_amount_(swaps_only)",
                "foreign_exchange_trade_forward_counter_currency_amount_(swaps_only)",
                "foreign_exchange_trade_foreign_exchange_rate_(swaps_only)",
                "foreign_exchange_trade_profit_/_loss",
                "foreign_exchange_trade_profit_/_loss_currency",
                "foreign_exchange_trade_profit_/_loss_reference_rate",
                "foreign_exchange_account_type",
                "foreign_exchange_account_number",
                "customer_deposit_exchange_deal_number",
                "customer_deposit_exchange_operation_direction",
                "customer_deposit_exchange_deal_date",
                "customer_deposit_exchange_value_date",
                "customer_deposit_exchange_principal_currency",
                "customer_deposit_exchange_principal",
                "customer_deposit_exchange_interest_rate",
                "customer_deposit_exchange_calculation_basis",
                "customer_deposit_exchange_maturity_date",
                "customer_deposit_exchange_deposit_creation_reason",
                "customer_deposit_exchange_rollover_information",
                "customer_foreign_exchange_account_type",
                "customer_foreign_exchange_account_number",
                "customer_deposit_contract_reference",
                "customer_deposit_current_event_reference",
                "customer_deposit_operation_direction",
                "customer_deposit_deal_date",
                "customer_deposit_value_date",
                "customer_deposit_operation_currency",
                "customer_deposit_principal_amount",
                "customer_deposit_global_interest_rate",
                "customer_deposit_old_interest_rate",
                "customer_deposit_interests_processing_type",
                "customer_deposit_calculation_basis",
                "customer_deposit_maturity_date",
                "customer_deposit_maturity_amount",
                "customer_deposit_deposit_creation_reason",
                "customer_deposit_accrued_interests",
                "customer_deposit_capital_increased_with_contract",
                "customer_deposit_customer_deposit_list_costs_details",
                "account_iban",
                "account_kbl_account_number",
                "account_client_name",
                "account_account_title",
                "account_account_type",
                "account_account_currency",
                "ca_instrument_kbl_code_identifying_security_used",
                "ca_instrument_isin_code",
                "ca_instrument_telekurs_code",
                "ca_instrument_sedol_code",
                "ca_instrument_description_of_security",
                "ca_instrument_type_of_financial_instrument",
                "ca_instrument_complementary_type",
                "ca_instrument_expression_type",
                "ca_instrument_currency_code",
                "ca_instrument_vni_frequency",
                "ca_instrument_place_of_listing",
                "ca_instrument_calculation_basis",
                "ca_instrument_contract_size",
                "ca_instrument_strike_price",
                "ca_instrument_currency_strike_price",
                "ca_instrument_maturity_date",
                "ca_instrument_interest_type",
                "ca_instrument_interest_rate_in_percentage",
                "ca_instrument_coupon_periodicity_(dd/mm)",
                "ca_instrument_coupon_maturity",
                "ca_instrument_issue_date",
                "ca_instrument_issue_nominal_amount",
                "ca_instrument_issue_nominal_amount_currency",
                "ca_instrument_indicator_issue_emission",
                "ca_instrument_indicateur_equalization_factor",
                "ca_instrument_rating_s&p",
                "ca_instrument_economic_sector",
                "ca_trade_ca_reference",
                "ca_trade_swift_official_reference",
                "ca_trade_status_code",
                "ca_trade_corporate_action_type_code",
                "ca_trade_corporate_action_type_description",
                "ca_trade_corporate_action_participation",
                "ca_trade_execution_date",
                "ca_trade_gross_amount",
                "ca_trade_gross_amount_currency",
                "ca_trade_net_amount",
                "ca_trade_net_amount_currency",
                "ca_trade_value_date",
                "ca_trade_securities_quantity",
                "ca_trade_rate",
                "ca_trade_gross_amount_exchange_rate",
                "ca_trade_customer_net_amount",
                "ca_trade_customer_net_amount_currency",
                "ca_trade_corporate_action_list_costs_details",
                "custody_trade_instruction_type",
                "custody_trade_instruction_external_reference",
                "custody_trade_operation_external_reference",
                "custody_trade_reception_date",
                "custody_trade_instruction_origin",
                "custody_trade_value_date",
                "custody_trade_settlement_date",
                "custody_trade_effective_settlement_date",
                "custody_trade_source_securities_account",
                "custody_trade_target_securities_account",
                "custody_trade_securities_quantity"
            ),
            cols_raw = NULL,
            date_cols = "AUTO_DATE_COLS",
            date_formats = c("%d.%m.%Y"),
            add_filename_date = TRUE,
            filename_date_col = "as_of_date",
            filename_date_fmt = "%Y-%m-%d",
            filename_date_regex = "JRN_([0-9]{4}-[0-9]{2}-[0-9]{2})_",
            sep = ";"
        ),
        db = list(
            table = "cashmovements",
            keys = c("common_client_id", "common_transaction_reference", "common_value_date", "common_transaction_currency")
        )
    ),

    sctiesstmt = list(
        file = list(
            pattern = "^G000359_.*_Global_SctiesStmt_JRN_[0-9]{4}-[0-9]{2}-[0-9]{2}_.*_CSV\\.csv$",
            cols_raw_src = c(
                "common_client id",
                "common_client name",
                "common_transaction reference",
                "common_balance quantity",
                "common_balance date",
                "common_transaction name",
                "common_transaction quantity",
                "common_accounting date",
                "common_value date",
                "common_statement number",
                "kbl code identifying security used",
                "isin code",
                "telekurs code",
                "sedol code",
                "description of security",
                "type of financial instrument",
                "complementary type",
                "expression type",
                "currency code",
                "vni frequency",
                "place of listing",
                "calculation basis",
                "contract size",
                "strike price",
                "currency strike price",
                "maturity date",
                "interest type",
                "interest rate in percentage",
                "coupon periodicity",
                "coupon maturity",
                "issue date",
                "issue nominal amount",
                "issue nominal amount currency",
                "indicator issue emission",
                "indicateur equalization factor",
                "rating s&p",
                "economic sector",
                "investment_account_kbl account number",
                "investment_account_account name",
                "investment_account_client name",
                "cash_ account_iban",
                "cash_ account_kbl account number",
                "cash_ account_client name",
                "cash_ account_account title",
                "cash_ account_account type",
                "cash_ account_account currency",
                "cost_list costs details",
                "cost_operation type",
                "cost_reference price",
                "cost_reference price unit",
                "cost_quantity",
                "cost_starting date",
                "cost_status",
                "cost_fee rate",
                "cost_fee amount if paid",
                "security_delivery_kb operation id",
                "security_delivery_client operation reference",
                "security_delivery_trade status",
                "security_delivery_trade date",
                "security_delivery_swift notification date",
                "security_delivery_place of trade",
                "security_delivery_settlement date",
                "security_delivery_effective settlement date",
                "security_delivery_operation direction",
                "security_delivery_quantity",
                "security_delivery_amount",
                "security_delivery_amount currency",
                "trade_instruction type",
                "trade_instruction external reference",
                "trade_operation external reference",
                "trade_reception date",
                "trade_instruction origin",
                "trade_value date",
                "trade_settlement date",
                "trade_effective settlement date",
                "trade_source securities account",
                "trade_target securities account",
                "trade_securities quantity",
                "settlement operation status",
                "counterparty type",
                "counterparty",
                "securities account identifier",
                "processing reference",
                "corporate_action_ca reference",
                "corporate_action_swift official reference",
                "corporate_action_status code",
                "corporate_action_corporate action type code",
                "corporate_action_corporate action type description",
                "corporate_action_corporate action participation",
                "corporate_action_execution date",
                "corporate_action_gross amount",
                "corporate_action_gross amount currency",
                "corporate_action_net amount",
                "corporate_action_net amount currency",
                "corporate_action_value date",
                "corporate_action_securities quantity",
                "corporate_action_rate",
                "corporate_action_gross amount exchange rate",
                "corporate_action_customer net amount",
                "corporate_action_customer net amount currency",
                "corporate_action_isin before ca",
                "corporate_action_rate new to old",
                "corporate_action_corporate action list costs details"
            ),
            cols_raw = NULL,
            date_cols = "AUTO_DATE_COLS",
            date_formats = c("%d.%m.%Y"),
            add_filename_date = TRUE,
            filename_date_col = "as_of_date",
            filename_date_fmt = "%Y-%m-%d",
            filename_date_regex = "JRN_([0-9]{4}-[0-9]{2}-[0-9]{2})_",
            sep = ";"
        ),
        db = list(
            table = "securitymovements",
            keys = c("common_client id", "common_transaction reference", "common_value date", "isin code")
        )
    ),

    solcptcsh = list(
        file = list(
            pattern = "^G000359_.*_Global_SolCptCsh_JRN_[0-9]{4}-[0-9]{2}-[0-9]{2}_.*_CSV\\.csv$",
            cols_raw = c(
                "client_id",
                "accounting_balance",
                "accounting_balance_eur",
                "value_date",
                "balance_at_value_date",
                "balance_at_value_date_eur",
                "exchange_values_rate",
                "last_booking_date",
                "iban",
                "kbl_cash_account_number",
                "client_name",
                "account_title",
                "account_type",
                "account_currency",
                "future_date_d+1",
                "future_position_d+1",
                "future_date_d+2",
                "future_position_d+2",
                "future_date_d+3",
                "future_position_d+3"
            ),
            date_cols = "AUTO_DATE_COLS",
            date_formats = c("%d.%m.%Y"),
            add_filename_date = TRUE,
            filename_date_col = "as_of_date",
            filename_date_fmt = "%Y-%m-%d",
            filename_date_regex = "JRN_([0-9]{4}-[0-9]{2}-[0-9]{2})_",
            sep = ";"
        ),
        db = list(
            table = "cashpositions",
            keys = c("client_id", "kbl_cash_account_number", "value_date", "account_currency", "as_of_date")
        )
    ),

    solcpttit = list(
        file = list(
            pattern = "^G000359_.*_Global_SolCptTit_JRN_[0-9]{4}-[0-9]{2}-[0-9]{2}_.*_CSV\\.csv$",
            cols_raw = c(
                "client_id",
                "value_date",
                "balance",
                "balance_at_value_date",
                "weighted_average_cost",
                "wac_currency",
                "accrued_interest",
                "ai_currency",
                "cash_evaluation",
                "cash_evaluation_currency",
                "countervalue",
                "countervalue_currency",
                "kbl_code_identifying_security_used",
                "isin_code",
                "telekurs_code",
                "sedol_code",
                "bloomberg_code",
                "reuters_code",
                "description_of_security",
                "type_of_financial_instrument",
                "complementary_type",
                "expression_type",
                "currency_code",
                "instrument_cash_evaluation",
                "instrument_cash_evaluation_currency",
                "vni_frequency",
                "place_of_listing",
                "calculation_basis",
                "contract_size",
                "strike_price",
                "currency_strike_price",
                "maturity_date",
                "interest_type",
                "interest_rate_in_percentage",
                "coupon_periodicity",
                "coupon_maturity",
                "issue_date",
                "issue_nominal_amount",
                "issue_nominal_amount_currency",
                "indicator_issue_emission",
                "indicateur_equalization_factor",
                "rating_s&p",
                "economic_sector",
                "kbl_account_number",
                "account_name",
                "client_name",
                "lendability_indicator",
                "lendability_starting_date",
                "lendability_ending_date",
                "lendable_quantity",
                "lent_quantity"
            ),
            date_cols = "AUTO_DATE_COLS",
            date_formats = c("%d.%m.%Y"),
            add_filename_date = TRUE,
            filename_date_col = "as_of_date",
            filename_date_fmt = "%Y-%m-%d",
            filename_date_regex = "JRN_([0-9]{4}-[0-9]{2}-[0-9]{2})_",
            sep = ";"
        ),
        db = list(
            table = "securitypostions",
            keys = c("client_id", "kbl_account_number", "isin_code", "value_date", "as_of_date")
        )
    )
)

cfg$cshstmt$file$cols_raw <- shorten_quintet_cols(cfg$cshstmt$file$cols_raw_src)
cfg$sctiesstmt$file$cols_raw <- shorten_quintet_cols(cfg$sctiesstmt$file$cols_raw_src)
