cfg <- list(
    cash = list(
        file = list(
            pattern = "^EDRCH.*cash\\.csv$",
            cols_raw = c(
                "rm_desk",
                "rm_code",
                "bp_code",
                "bp_iso_currency",
                "container_code",
                "container_iso_currency",
                "current_account_code",
                "asset_id",
                "isin",
                "asset_name",
                "asset_group",
                "asset_iso_currency",
                "record_date",
                "value_date",
                "trade_date",
                "operation_number",
                "order_number",
                "flag_reversal",
                "operation_type",
                "order_type",
                "operation_description",
                "sender_receiver_account",
                "quantity",
                "fx_rate_container_ccy",
                "fx_rate_bp_ccy",
                "fx_rate_bu_ccy",
                "gross_amount_in_asset_currency",
                "fees_in_asset_currency",
                "net_amount_in_asset_currency",
                "gross_amount_in_container_currency",
                "fees_in_container_currency",
                "net_amount_in_container_currency",
                "gross_amount_in_bp_currency",
                "fees_in_bp_currency",
                "net_amount_in_bp_currency",
                "gross_amount_in_bu_currency",
                "fees_in_bu_currency",
                "net_amount_in_bu_currency",
                "external_reference",
                "commission_in_asset_currency",
                "commission_in_container_currency",
                "commission_in_bu_currency",
                "external_commission_in_asset_currency",
                "external_commission_in_container_currency",
                "external_commission_in_bu_currency",
                "fee_in_asset_currency",
                "fee_in_container_currency",
                "fee_in_bu_currency",
                "external_fees_in_asset_currency",
                "external_fees_in_container_currency",
                "external_fees_in_bu_currency",
                "vat_in_asset_currency",
                "vat_in_container_currency",
                "vat_in_bu_currency",
                "stamp_in_asset_currency",
                "stamp_in_container_currency",
                "stamp_in_bu_currency",
                "interest_in_asset_currency",
                "interest_in_container_currency",
                "interest_in_bu_currency",
                "eu_in_asset_currency",
                "eu_in_container_currency",
                "eu_in_bu_currency",
                "wtax_in_asset_currency",
                "wtax_in_container_currency",
                "wtax_in_bu_currency",
                "source_tax_in_asset_currency",
                "source_tax_in_container_currency",
                "source_tax_in_bu_currency",
                "complementary_in_asset_currency",
                "complementary_in_container_currency",
                "complementary_in_bu_currency",
                "retro_in_asset_currency",
                "retro_in_container_currency",
                "retro_in_bu_currency",
                "linked_asset_id",
                "currency_of_linked_asset",
                "execution_time",
                "beneficiary_account_reference",
                "linked_fx_reference",
                "fx_trade_rate"
            ),
            date_cols = c("record_date", "value_date", "trade_date"),
            date_formats = c("%d.%m.%Y"),
            sep = ";"
        ),
        db = list(
            table = "cashpositions",
            keys = c("bp_code", "bp_iso_currency", "asset_iso_currency", "value_date", "trade_date", "operation_number", "order_number")
        )
    ),

    securities = list(
        file = list(
            pattern = "^EDRCH.*securities\\.csv$",
            cols_raw = c(
                "rm_desk",
                "rm_code",
                "bp_code",
                "bp_iso_currency",
                "container_code",
                "container_iso_currency",
                "asset_id",
                "isin",
                "bloomberg_ticker",
                "asset_name",
                "market_name",
                "asset_group",
                "asset_country",
                "asset_economical_sector",
                "s&p_rating",
                "asset_iso_currency",
                "maturity_date",
                "record_date",
                "value_date",
                "trade_date",
                "operation_number",
                "order_number",
                "flag_reversal",
                "in_/_out",
                "order_type",
                "operation_type",
                "custodian_id",
                "custodian_name",
                "quantity",
                "price",
                "fx_rate_container_ccy",
                "fx_rate_bp_ccy",
                "fx_rate_bu_ccy",
                "gross_amount_in_asset_currency",
                "fees_in_asset_currency",
                "net_amount_in_asset_currency",
                "gross_amount_in_container_currency",
                "fees_in_container_currency",
                "net_amount_in_container_currency",
                "gross_amount_in_bp_currency",
                "fees_in_bp_currency",
                "net_amount_in_bp_currency",
                "interest_in_bp_currency",
                "gross_amount_in_bu_currency",
                "fees_in_bu_currency",
                "net_amount_in_bu_currency",
                "external_reference",
                "quotation_type",
                "commission_in_asset_currency",
                "commission_in_container_currency",
                "commission_in_bu_currency",
                "external_commission_in_asset_currency",
                "external_commission_in_container_currency",
                "external_commission_in_bu_currency",
                "fee_in_asset_currency",
                "fee_in_container_currency",
                "fee_in_bu_currency",
                "external_fees_in_asset_currency",
                "external_fees_in_container_currency",
                "external_fees_in_bu_currency",
                "vat_in_asset_currency",
                "vat_in_container_currency",
                "vat_in_bu_currency",
                "stamp_in_asset_currency",
                "stamp_in_container_currency",
                "stamp_in_bu_currency",
                "interest_in_asset_currency",
                "interest_in_container_currency",
                "interest_in_bu_currency",
                "eu_in_asset_currency",
                "eu_in_container_currency",
                "eu_in_bu_currency",
                "wtax_in_asset_currency",
                "wtax_in_container_currency",
                "wtax_in_bu_currency",
                "source_tax_in_asset_currency",
                "source_tax_in_container_currency",
                "source_tax_in_bu_currency",
                "complementary_in_asset_currency",
                "complementary_in_container_currency",
                "complementary_in_bu_currency",
                "retro_in_asset_currency",
                "retro_in_container_currency",
                "retro_in_bu_currency"
            ),
            date_cols = c("maturity_date", "record_date", "value_date", "trade_date"),
            date_formats = c("%d.%m.%Y"),
            sep = ";"
        ),
        db = list(
            table = "securities",
            keys = c("isin", "asset_name"),
            dedupe_keys = c("isin", "asset_name")
        )
    ),

    positions = list(
        file = list(
            pattern = "^EDRCH.*positions\\.csv$",
            cols_raw = c(
                "rm_desk",
                "rm_code",
                "external_asset_manager_code",
                "bp_code",
                "bp_iso_currency",
                "container_code",
                "container_iso_currency",
                "asset_id",
                "isin",
                "asset_name",
                "asset_type",
                "asset_iso_currency",
                "bloomberg_ticker",
                "s&p_rating",
                "asset_country",
                "asset_industry",
                "asset_economical_sector",
                "contract_code",
                "buy_currency",
                "sell_currency",
                "fx_contract_operation_type",
                "postions_id",
                "position_type",
                "position_iso_currency",
                "current_account_code",
                "last_booking_date",
                "reference_date",
                "asset_price_date",
                "maturity_date",
                "fx_rate_container_ccy",
                "fx_rate_bp_ccy",
                "fx_rate_bu_ccy",
                "asset_rate",
                "average_cost_price",
                "average_cost_price_in_container_currency",
                "price",
                "quantity",
                "cost_amount",
                "annual_coupons_amount",
                "p/l_in_%",
                "weight",
                "accrued_interests_in_position_currency",
                "valuation_in_position_currency",
                "accrued_interests_in_container_currency",
                "valuation_in_container_currency",
                "accrued_interests_in_bp_currency",
                "valuation_in_bp_currency",
                "accrued_interests_in_bu_currency",
                "valuation_in_bu_currency",
                "total_accrued_interests_in_container_currency",
                "aum_net_without_accrued_interests_in_container_currency",
                "aum_net_in_container_currency",
                "aum_net_in_bu_currency",
                "quotation_type",
                "strike_price",
                "iban"
            ),
            date_cols = c("last_booking_date", "reference_date", "asset_price_date", "maturity_date"),
            date_formats = c("%d.%m.%Y"),
            sep = ";"
        ),
        db = list(
            table = "securitypositions",
            keys = c("bp_code", "bp_iso_currency", "isin", "asset_name", "position_iso_currency", "reference_date", "quantity")
        )
    ),

    perf = list(
        file = list(
            pattern = "^EDRCH.*perf\\.csv$",
            cols_raw = c(
                "rm_desk",
                "rm_code",
                "reference_date",
                "bp_code",
                "bp_iso_currency",
                "container_code",
                "container_iso_currency",
                "container_open_date",
                "container_close_date",
                "management_profile",
                "performance_period",
                "aum_gross_in_container_currency",
                "total_accrued_interests_in_container_currency",
                "aum_net_in_container_currency",
                "aum_net_in_bu_currency",
                "incoming_ytd_in_container_currency",
                "incoming_ytd_in_bu_currency",
                "outgoing_ytd_in_container_currency",
                "outgoing_ytd_in_bu_currency",
                "incoming_mtd_in_container_currency",
                "incoming_mtd_in_bu_currency",
                "outgoing_mtd_in_container_currency",
                "outgoing_mtd_in_bu_currency",
                "incoming_dly_in_container_currency",
                "incoming_dly_in_bu_currency",
                "outgoing_dly_in_container_currency",
                "outgoing_dly_in_bu_currency",
                "twr_gross_ytd_in_container_currency",
                "twr_net_ytd_in_container_currency",
                "twr_net_mtd_in_container_currency",
                "twr_net_dly_in_container_currency",
                "unrealized_p/l_ytd_in_container_currency",
                "unrealized_p/l_mtd_in_container_currency",
                "unrealized_p/l_dly_in_container_currency",
                "incoming_ytd_in_bp_currency",
                "outgoing_ytd_in_bp_currency",
                "incoming_mtd_in_bp_currency",
                "outgoing_mtd_in_bp_currency",
                "incoming_dly_in_bp_currency",
                "outgoing_dly_in_bp_currency",
                "twr_net_ytd_in_bp_currency",
                "twr_net_mtd_in_bp_currency",
                "twr_net_dly_in_bp_currency",
                "unrealized_p/l_ytd_in_bp_currency",
                "unrealized_p/l_mtd_in_bp_currency",
                "unrealized_p/l_dly_in_bp_currency",
                "sop_aum_net_in_reference_currency"
            ),
            date_cols = c("as_of_date", "reference_date", "container_open_date", "container_close_date"),
            add_filename_date = TRUE,
            filename_date_col = "as_of_date",
            filename_date_fmt = "%Y%m%d",
            filename_date_regex = "([0-9]{8})_perf\\.csv$",
            date_formats = c("%d.%m.%Y"),
            sep = ";"
        ),
        db = list(
            table = "clientdetails",
            keys = c("as_of_date", "reference_date", "bp_code", "bp_iso_currency")
        )
    ),

    orderbook = list(
        file = list(
            pattern = "^EDRCH.*orderbook\\.csv$",
            cols_raw = c(
                "rm_desk",
                "rm_code",
                "bp_code",
                "bp_iso_currency",
                "container_code",
                "container_iso_currency",
                "asset_id",
                "isin",
                "asset_name",
                "asset_group",
                "asset_iso_currency",
                "bloomberg_ticker",
                "operation_number",
                "order_number",
                "flag_reversal",
                "order_type",
                "record_date",
                "trade_date",
                "value_date",
                "price",
                "quantity",
                "gross_amount_in_asset_currency",
                "interest_in_asset_currency",
                "limit_price",
                "order_status",
                "external_reference",
                "visible_size",
                "trigger_price"
            ),
            date_cols = c("record_date", "trade_date", "value_date"),
            date_formats = c("%d.%m.%Y"),
            add_filename_date = TRUE,
            filename_date_col = "as_of_date",
            filename_date_fmt = "%Y%m%d",
            filename_date_regex = "([0-9]{8}).*orderbook\\.csv$",
            sep = ";"
        ),
        db = list(
            table = "orderbook",
            keys = c("bp_code", "bp_iso_currency", "isin", "asset_name", "asset_iso_currency", "operation_number", "trade_date", "as_of_date")
        )
    )
)
